version: "3.8"
services:
    angulardocker:
        container_name: angular-container
        build: .
        volumes: 
            - .:/app
        ports: 
            - 4200:4200
        command: 
            bash -c "ng serve --host=0.0.0.0" 
